source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HPUIViewExtensionsObjC_Example', :exclusive => true do
  pod "HPUIViewExtensionsObjC", :path => "../"
end

target 'HPUIViewExtensionsObjC_Tests', :exclusive => true do
  pod "HPUIViewExtensionsObjC", :path => "../"

  
end
